greeting: 0
parking: 1
printer: 2
start: 3
help: 4
book: 5
print: 6
list: 7

message:
  handlerProperties:
    - description: Возвращает пользователю в главное меню
      key: /start
      value: "Привет, я бот помощник.\nИспользуй клавиатуру чтобы сделать офис *УМНЫМ* \uD83E\uDD13"
    - description: Возвращает пользователю информацию про парковочные места
      key: "Парковка"
      value: "*Свободных места*: {0}\n\n*Занятых места*: {1}\n\n*Всего мест*: {2}"
    - description: Печатает документы которые вы приложите к команде
      key: "Принтер"
      value: "Приложите документ (PDF/ JPEG)"
    - description: Возвращает в главное меню
      key: "В начало"
      value: "Главное меню"
    - description: Помощь по использованию бота
      key: "Помощь"
      value: ""
    - description: Бронирует место на парковке
      key: "Забронировать"
      value: "Место успешно забронировано"
    - description: Печатает документ
      key: ""
      value: "Документ успешно распечатан"
    - description: Выдает список пользователей забронировавших места
      key: "Кто забронировал?"
      value: "Места забронировали: \n{0}"
